# baseurl value changed from "/" to "" for the purposes of running on AWS Cloud9.
url: https://compilerla.github.io
baseurl: ""

# Site settings
title: School of Data LA
email: data-donuts@compiler.la
description: "School of Data LA is a two day training event organized by the team that brings you Data + Donuts every month."
address: ""
twitter: datadonutsla
github: compilerla/school-of-data
youtube: channel/UC_mAa07EdkkGCn48lq0yj3Q/
linkedin: 
docs: 

# Location Block
locationBlockTitle: "Venue"
eventLocationName: "Souther California Association of Governments Office<br> @ Wilshire Grand Center"
eventLocationLink: "http://www.wilshiregrandcenter.com/"
eventStreetAddress: "900 Wilshire Blvd., Ste. 1700"
eventAddressLocality: "Los Angeles, CA"
eventAddressLocalityRegion: "USA"
eventPostalCode: "90017"
eventAddressCountry: "United States"
eventStartTime: "2019-01-31T08:00"
eventDoorTime: "08:00"
eventEndTime: "2019-02-01T17:00"
eventPlaceCoordinates: "34.0497172, -118.2628073"


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll


# Build settings
markdown: kramdown
permalink: pretty